version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bdteste
      - DB_USERNAME=php_root
      - DB_PASSWORD=password

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bdteste
      MYSQL_USER: php_root
      MYSQL_PASSWORD: password
    volumes:
    - ./database/bdteste.sql:/docker-entrypoint-initdb.d/bdteste.sql
    ports:
      - "3307:3306"
